[Misc]
UpdateReminderTime = "30s"
ImScaredOfUpdates = false

[General]
Description = "Monaco GP - beamdash managed"
MaxCars = 4
LogChat = true
ResourceFolder = "Resources"
IP = "::"
Name = "beamdash Monaco GP Server"
Private = false
InformationPacket = true
AllowGuests = true
Port = 30814
Debug = false
Tags = "Race,Monaco"
AuthKey = "CHANGE_ME"
MaxPlayers = 8
Map = "/levels/monaco2/info.json"
